version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mindrot:jbcrypt
    versions:
    - "> 0.4, < 1"
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jooq:jooq
    versions:
    - 3.14.6
    - 3.14.7
    - 3.14.8
  - dependency-name: org.jooq:jooq-codegen
    versions:
    - 3.14.6
    - 3.14.7
    - 3.14.8
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.19
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.5
    - 1.10.6
  - dependency-name: org.testcontainers:selenium
    versions:
    - 1.15.2
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.2
  - dependency-name: io.kotest:kotest-plugins-pitest
    versions:
    - 4.4.0
    - 4.4.0.RC3
  - dependency-name: io.kotest:kotest-property
    versions:
    - 4.4.0
    - 4.4.0.RC3
  - dependency-name: io.kotest:kotest-runner-junit5
    versions:
    - 4.4.0
    - 4.4.0.RC3
