# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# to run your custom scripts instead of automatic MSBuild
build_script:
  - mvnw.cmd clean test org.pitest:pitest-maven:mutationCoverage package
environment:
  matrix:
    - JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
    - JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
services:
  - postgresql94
cache:
  - '%USERPROFILE%\.m2'
install:
  - cmd: SET PGUSER=postgres
  - cmd: SET PGPASSWORD=Password12!
  - cmd: PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
  - cmd: createdb crm
